---
#run on all hosts
- hosts: all
  become: true
  pre_tasks:

#check and update the packages on all hosts
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    #when: ansible_distribution == "Ubuntu"

#Setup Monitoring with Prometheus and Grafana: Installs Prometheus and Grafana, configures them to start on boot, and sets up firewall rules to allow traffic.
#- import_playbook: test.yml
- import_playbook: install_prometheus_grafana.yml 

