---
- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted    

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true